services:
  - type: web
    name: windsurf-keycloak
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /auth/realms/master
    port: 8080
    plan: starter
    envVars:
      - key: KEYCLOAK_ADMIN
        sync: false
      - key: KEYCLOAK_ADMIN_PASSWORD
        sync: false
      - key: DB_VENDOR
        value: postgres
      - key: DB_ADDR
        value: dpg-d0hv6bemcj7s739hscc0-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: keycloak_l3wn
      - key: DB_USER
        value: keycloak_l3wn_user
      - key: DB_PASSWORD
        value: exBGAs0x5CDliJCt6vbmDZApVkcVLV0m
      - key: PROXY_ADDRESS_FORWARDING
        value: "true"
      - key: KC_HOSTNAME
        sync: false
    disk:
      name: keycloak-data
      mountPath: /opt/keycloak/data
      sizeGB: 1
