services:
  - type: web
    name: windsurf-keycloak
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: KEYCLOAK_ADMIN
        sync: false
      - key: KEYCLOAK_ADMIN_PASSWORD
        sync: false
      - key: KC_DB_URL
        sync: false
      - key: KC_DB_USERNAME
        sync: false
      - key: KC_DB_PASSWORD
        sync: false
      - key: KC_HOSTNAME
        sync: false
    disk:
      name: keycloak-data
      mountPath: /opt/keycloak/data
      sizeGB: 1
