services:
  - type: web
    name: windsurf-keycloak
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health/ready
    port: 8080
    plan: starter
    envVars:
      - key: KEYCLOAK_ADMIN_USER
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        sync: false
      - key: KEYCLOAK_DATABASE_HOST
        value: dpg-d0hv6bemcj7s739hscc0-a
      - key: KEYCLOAK_DATABASE_PORT
        value: "5432"
      - key: KEYCLOAK_DATABASE_NAME
        value: keycloak_l3wn
      - key: KEYCLOAK_DATABASE_USER
        value: keycloak_l3wn_user
      - key: KEYCLOAK_DATABASE_PASSWORD
        value: exBGAs0x5CDliJCt6vbmDZApVkcVLV0m
      - key: KEYCLOAK_PROXY
        value: edge
      - key: KEYCLOAK_PRODUCTION
        value: "false"
      - key: KEYCLOAK_HTTP_RELATIVE_PATH
        value: "/"
    disk:
      name: keycloak-data
      mountPath: /opt/keycloak/data
      sizeGB: 1
